### PR TITLE
Support Magicitems module

### LINKED ISSUE #5: Wondrous items not parsing charges
**Reported by:** Jacket on **Source:** [VTTAssets Discord](https://discordapp.com/channels/613704572782903312/684500792433967105/685143659611553847)
  

  
> https://www.dndbeyond.com/magic-items/ring-of-evasion
  
**Attachments:** [ring-of-evasion.json](https://cdn.discordapp.com/attachments/684500792433967105/685143659707891725/ring-of-evasion.json)
  
Forgive me if this has already been brought up or asked about, but when parsing character items other it looks like equipped magic items don't retain their charge information and instead become loot:
https://cdn.discordapp.com/attachments/625267799928995840/684814324539326497/beyond.PNG
https://cdn.discordapp.com/attachments/625267799928995840/684814417703206920/unknown.png
This should be the relevant JSON I think:
```
limitedUse": {
                    "maxUses": 3,
                    "numberUsed": 0,
                    "resetType": "Dawn",
                    "resetTypeDescription": "Regains 1d3 expended charges daily at dawn"
}```

### PR DESCRIPTION
**Pull request by MrPrimate**
Extends https://github.com/VTTAssets/vtta-dndbeyond/pull/31

- Wands, rods, wondrous items etc are imported as equipment types.
- start on using the magic item extension for providing these spells.
- spells are imported as always available.
- item spells have the item name in there name.
- they use charges on the item, and this might not always be a good match if the item has multiple spells. But better than nothing. 
- *However* if the magicitems module https://gitlab.com/riccisi/foundryvtt-magic-items/ is installed.
- Stop fetching uses on weapons etc as this limits their use as weapons.
- Break up of a couple of big pieces of functionality into class methods
- Filter to check for magicitem module and import metadata if it exists.

Resolves #5 

Example without magicitems module:

With magicitems module:

### CODE REVIEW

**Comment by MrPrimate** [comment]
Hmm, this doesn't quite work on the checking to see if the module exists! I need to check my logic/async stuff and fix.

**Comment by MrPrimate** [comment]
So I was testing something else in Firefox, and something doesn't quite work right there:

```
SyntaxError: invalid regexp group magicify.js:1:9
```
Need to figure out why these simple regex work in Chrome but not FF!

**Comment by MrPrimate** [comment]
It's this https://bugzilla.mozilla.org/show_bug.cgi?id=1362154 will need to remove named groups.

**Comment by MrPrimate** [comment]
Okay, resolved and ready again for review

**Comment by VTTAssets** [comment]
You can use the Map `game.modules` to check if a module is installed, e.g. `game.modules.get('magicitems') !== undefined` during run-time.

Being "dependant" on foreign modules is a small paradigm shift, as I want to support vanilla Foundry, so not too sure about that change. 

I will need some more time to really dig into the code, thanks for your contributions, those are generally great!

**Comment by MrPrimate** [comment]
Ah! Thanks, missed that, I'll push a change soon. I have tried to keep true to your vision - in that two modes are supported, if it can't find the module then it loads the spells as best it can.

**Comment by VTTAssets** [comment]
I am merging this change because I think it brings a lot of value to the imported data. I will inform the magicitems-module author about that integration and see if he commits to developing his mod in the future, it would be great until Foundry brings such things into core. 

Thanks again for your contributions!

**Pull request merged**
